cnijfilter-common.spec: fixes to build on F40
1. Add empty LDFLAGS to fix a configure error:

checking whether we are cross compiling... configure: error: in `/home/kir/rpmbuild/BUILD/cnijfilter-source-3.80-2/cnijfilter':
configure: error: cannot run C compiled programs.

2. Add "%global _missing_build_ids_terminate_build 0" to fix:

error: Missing build-id in /home/kir/rpmbuild/BUILDROOT/cnijfilter-mg6300series-3.80-2.x86_64/usr/lib64/libcnbpcmcm408.so.8.10.1
error: Missing build-id in /home/kir/rpmbuild/BUILDROOT/cnijfilter-mg6300series-3.80-2.x86_64/usr/lib64/libcnbpcnclapi408.so.3.8.0
error: Missing build-id in /home/kir/rpmbuild/BUILDROOT/cnijfilter-mg6300series-3.80-2.x86_64/usr/lib64/libcnbpcnclbjcmd408.so.3.3.0
error: Missing build-id in /home/kir/rpmbuild/BUILDROOT/cnijfilter-mg6300series-3.80-2.x86_64/usr/lib64/libcnbpcnclui408.so.3.8.0
error: Missing build-id in /home/kir/rpmbuild/BUILDROOT/cnijfilter-mg6300series-3.80-2.x86_64/usr/lib64/libcnbpess408.so.4.1.3
error: Missing build-id in /home/kir/rpmbuild/BUILDROOT/cnijfilter-mg6300series-3.80-2.x86_64/usr/lib64/libcnbpo408.so.1.0.1
error: Generating build-id links failed

3. Add %changelog to fix:

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>